export const config = {
  supportedStateIds: ['1s', '2s'],
  supportedNucleusModes: ['visibleReference', 'physical'],
  initialSuperposition: [{ n: 1, l: 0, m: 0, magnitude: 1, phase: 0 }],
  initialTime: 0.0,
  initialIsPlaying: false,
  initialTimeScale: 1.0,
  initialSampleCount: 2000000,
  minSampleCount: 1,
  defaultSeed: 12345,
  minSeed: 0,
  maxSeed: 0xffffffff,
  defaultTruncationRadius: 12,
  defaultPointSize: 0.01,
  minPointSize: 0.001,
  defaultOpacity: 0.11,
  minOpacity: 0,
  maxOpacity: 1,
  electronColor: 0x7ce7ff,
  initialNucleusMode: 'physical',
  physicalNucleusRadius: 0.02,
  visibleReferenceNucleusRadius: 0.3,
  nucleusColor: 0xffd38a,
  defaultCameraPosition: {
    x: 0,
    y: 0,
    z: 16,
  },
  cameraFovDegrees: 45,
  cameraNear: 0.1,
  cameraFar: 200,
  sceneBackgroundColor: 0x000000,
  rendererAntialias: true,
  controlsHelpText: 'Drag to orbit, right-drag or WASD to pan, and scroll to zoom.',
}
