export const config = {
  supportedStateIds: ['1s', '2s'],
  initialStateId: '1s',
  initialSampleCount: 20000,
  defaultSeed: 12345,
  defaultTruncationRadius: 12,
  defaultPointSize: 0.04,
  defaultOpacity: 0.2,
  electronColor: 0x7ce7ff,
  initialNucleusMode: 'visibleReference',
  physicalNucleusRadius: 0.02,
  visibleReferenceNucleusRadius: 0.3,
  nucleusColor: 0xffd38a,
  defaultCameraPosition: {
    x: 0,
    y: 0,
    z: 16,
  },
  cameraFovDegrees: 45,
  cameraNear: 0.1,
  cameraFar: 200,
  sceneBackgroundColor: 0x000000,
  rendererAntialias: true,
}
